apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: bookinfo-core-config
spec:
  git:
    type: github
    apiUrl: ""
    repository: tmax-cloud/bookinfo-core
    token:
      valueFrom:
        secretKeyRef:
          name: yxzzzxh-git-token
          key: token
  workspaces:
    - name : core-workspace
      persistentVolumeClaim:
        claimName: core-pvc
  secrets:
    - name : tmaxcloudck-docker-hub-secret
  jobs:
    postSubmit:
      - name: s2i-gradle-generate
        image: docker.io/tmaxcloudck/cicd-util:5.0.5
        env: 
          - name: JAR_NAME
            value : core.jar
        when:
          tag:
            - v.*
        script: |
          /usr/local/bin/s2i \
          build . docker.io/changjjjjjjjj/s2i-gradle-java:dev \
          --env JAR_NAME=$JAR_NAME \
          --tlsverify=false \
          --as-dockerfile $(workspaces.core-workspace.path)/Dockerfile.gen
      - name: build-and-push
        image: quay.io/buildah/stable
        script: |
          IMG_TAG=${CI_HEAD_REF#refs/tags/}

          buildah bud --tls-verify=false --storage-driver=vfs --format docker -f $(workspaces.core-workspace.path)/Dockerfile.gen -t $REGISTRY_URL/$IMG_PATH:$IMG_TAG $(workspaces.core-workspace.path)
          buildah login --tls-verify=false -u $REG_USER -p $REG_PASS $REGISTRY_URL
          buildah push --tls-verify=false --storage-driver=vfs $REGISTRY_URL/$IMG_PATH:$IMG_TAG docker://$REGISTRY_URL/$IMG_PATH:$IMG_TAG
        env:
          - name: REGISTRY_URL
            value: core.hr.172.22.11.16.nip.io
          - name: IMG_PATH
            value: shinhan-bookinfo/bookinfo-core
          - name: REG_USER
            value: admin
          - name: REG_PASS
            value: admin
        securityContext:
          privileged: true
        after:
          - s2i-gradle-generate
        when:
          tag:
            - v.*
